### ISSUE TITLE
code review 

### ISSUE THREAD

**Issue by haitham-akram** [GSG-G13/Autocomplete-Eman-Momen#28]
Hi @Emanalabsi , @Dev-MomenQudaih . You've done a great job! Keep going!! But I have some changes that you may consider in your future projects:
- There are some commented lines in https://github.com/GSG-G13/Autocomplete-Eman-Momen/blob/a6108617ca7c47e0854a3c4255f950f90c0b46da/public/index.js#L25
- In declaration variables, it's better to use const instead of let https://github.com/GSG-G13/Autocomplete-Eman-Momen/blob/a6108617ca7c47e0854a3c4255f950f90c0b46da/public/index.js#L1
- and there are some commented lines in CSS https://github.com/GSG-G13/Autocomplete-Eman-Momen/blob/a6108617ca7c47e0854a3c4255f950f90c0b46da/public/style.css#L105

Thank you and good luck!

**Comment by momenqudaih** [comment]
Thanks a lot @haitham-akram,  we will consider that in our future projects.❤️

Thank you and good luck for you also🌹
